"""telegram

Revision ID: e2fab2be656d
Revises: 0ec06badc28f
Create Date: 2026-04-15 00:54:21.025929

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e2fab2be656d"
down_revision: Union[str, Sequence[str], None] = "0ec06badc28f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("telegram_chat_id", sa.String(), nullable=True))
    op.drop_column("users", "phone_number")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("phone_number", sa.VARCHAR(), nullable=True))
    op.drop_column("users", "telegram_chat_id")
    # ### end Alembic commands ###
